### ISSUE TITLE
Cannot Run Models Other Than QwenV2 Due to Package Errors

### ISSUE THREAD

**Issue by marcolaurenzi** [HenryPengZou/ImplicitAVE#1]
**Description:**
I am facing issues running models other than QwenV2. It seems there are missing or incompatible dependencies, leading to package-related errors when attempting to execute them.

**Steps to Reproduce:**
	1.	Clone the repository and set up the environment following the README instructions.
	2.	Attempt to run a model other than QwenV2 (e.g., BLIP2).
	3.	Encounter package-related errors.

**Observed Behavior:**
	•	QwenV2 runs successfully without issues.
	•	Other models fail due to dependency errors.

**Expected Behavior:**
	•	All models should run without errors if their dependencies are correctly installed.

**Questions:**
	1.	Is there a separate requirements file or dependency list for each model, similar to the one for QwenV2?
	2.	If not, could you provide guidance on the necessary packages for the other models?

**Environment:**
	•	Operating System: <MacOS (notebooks running con Google Colab)>
	•	Python Version: <3.9>

**Error Logs:**
```
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-16-e99c413e996d>](https://i8fmlnft88-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20241125-104948_RC00_700020055#) in <cell line: 2>()
      1 processor = Blip2Processor.from_pretrained("Salesforce/blip2-flan-t5-xl")
----> 2 model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xl", load_in_4bit=True, device_map="auto")

1 frames
[/usr/local/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py](https://i8fmlnft88-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20241125-104948_RC00_700020055#) in validate_environment(self, *args, **kwargs)
     72             )
     73         if not is_bitsandbytes_available():
---> 74             raise ImportError(
     75                 "Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`"
     76             )

ImportError: Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`
```

**Comment by HenryPengZou** [comment]
Hi @marcolaurenzi, thanks for your interest in our work! Yes,  there is a separate requirements file or dependency list for each model. This repository only provides the environment setup guidance for Qwen-VL model. However, the environment setup guidance for each model can be found on their respective project page: 
* [BLIP-2](https://github.com/salesforce/LAVIS/tree/main/projects/blip2) ([Installation Link](https://github.com/salesforce/LAVIS/tree/main#installation))
* [InstructBLIP](https://github.com/salesforce/LAVIS/tree/main/projects/instructblip) ([Installation Link](https://github.com/salesforce/LAVIS/tree/main#installation))
* [GPT-4](https://platform.openai.com/docs/models) ([Quickstart Guide](https://platform.openai.com/docs/guides/text-generation))
* [LLaVA](https://github.com/haotian-liu/LLaVA?tab=readme-ov-file) ([Installation Link](https://github.com/salesforce/LAVIS/tree/main#installation))
* [Qwen-VL](https://github.com/QwenLM/Qwen-VL)
